version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install --user -r requirements.txt
      - run:
          name: Run tests
          command: python3.8 tests/bootstrap.py
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
