version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install --user -r requirements.txt
      - run:
          name: Run tests
          command: python2.7 tests/bootstrap.py

