version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/python:2.7.15
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install --user -r requirements.txt
      - run:
          name: Install future
          command: pip install --user future
      - run:
          name: Mock
          command: pip install --user mock
      - run:
          name: Run tests
          command: python2.7 tests/bootstrap.py
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
