version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python2.7 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python2.7 tests/bootstrap.py
            		

